version: '3.8'

services:
  clusterstateapi:
    image: cluster-state-api:latest
    container_name: clusterstateapi
    ports:
      - "8081:8081"
    volumes:
      - /Users/manaumenkos/dev/diplom/cluster-state-api/script/shards_strict.yaml:/app/config/shards.yaml
    networks:
      - mynet

  searchgatewayapi:
    image: search-gateway-api:latest
    container_name: searchgatewayapi
    environment:
      - CLUSTER_STATE_HOST=clusterstateapi
    ports:
      - "8080:8080"
    depends_on:
      - clusterstateapi
    networks:
      - mynet

  shardsearchservice-1:
    image: shard-search-api:latest
    container_name: shardsearchservice-1
    environment:
      - NODE_ID=node-1
      - CLUSTER_STATE_HOST=clusterstateapi
      - PORT=9091
      - FAISS_SHARD_IDS=1,3,5
    volumes:
      - /Users/manaumenkos/dev/diplom/transfer/data/shards6_smol:/app/data/lucene
      - /Users/manaumenkos/dev/diplom/transfer/data/shards6_smol/output:/data/faiss
    ports:
      - "9091:9091"
    depends_on:
      - clusterstateapi
    networks:
      - mynet

  shardsearchservice-2:
    image: shard-search-api:latest
    container_name: shardsearchservice-2
    environment:
      - NODE_ID=node-2
      - CLUSTER_STATE_HOST=clusterstateapi
      - PORT=9092
      - FAISS_SHARD_IDS=1,3,5
    volumes:
      - /Users/manaumenkos/dev/diplom/transfer/data/shards6_smol:/app/data/lucene
      - /Users/manaumenkos/dev/diplom/transfer/data/shards6_smol/output:/data/faiss
    ports:
      - "9092:9092"
    depends_on:
      - clusterstateapi
    networks:
      - mynet

  shardsearchservice-3:
    image: shard-search-api:latest
    container_name: shardsearchservice-3
    environment:
      - NODE_ID=node-3
      - CLUSTER_STATE_HOST=clusterstateapi
      - PORT=9093
      - FAISS_SHARD_IDS=1,3,5
    volumes:
      - /Users/manaumenkos/dev/diplom/transfer/data/shards6_smol:/app/data/lucene
      - /Users/manaumenkos/dev/diplom/transfer/data/shards6_smol/output:/data/faiss
    ports:
      - "9093:9093"
    depends_on:
      - clusterstateapi
    networks:
      - mynet

  shardsearchservice-4:
    image: shard-search-api:latest
    container_name: shardsearchservice-4
    environment:
      - NODE_ID=node-4
      - CLUSTER_STATE_HOST=clusterstateapi
      - PORT=9094
      - FAISS_SHARD_IDS=0,2,4
    volumes:
      - /Users/manaumenkos/dev/diplom/transfer/data/shards6_smol:/app/data/lucene
      - /Users/manaumenkos/dev/diplom/transfer/data/shards6_smol/output:/data/faiss
    ports:
      - "9094:9094"
    depends_on:
      - clusterstateapi
    networks:
      - mynet

  shardsearchservice-5:
    image: shard-search-api:latest
    container_name: shardsearchservice-5
    environment:
      - NODE_ID=node-5
      - CLUSTER_STATE_HOST=clusterstateapi
      - PORT=9095
      - FAISS_SHARD_IDS=0,2,4
    volumes:
      - /Users/manaumenkos/dev/diplom/transfer/data/shards6_smol:/app/data/lucene
      - /Users/manaumenkos/dev/diplom/transfer/data/shards6_smol/output:/data/faiss
    ports:
      - "9095:9095"
    depends_on:
      - clusterstateapi
    networks:
      - mynet

  shardsearchservice-6:
    image: shard-search-api:latest
    container_name: shardsearchservice-6
    environment:
      - NODE_ID=node-6
      - CLUSTER_STATE_HOST=clusterstateapi
      - PORT=9096
      - FAISS_SHARD_IDS=0,2,4
    volumes:
      - /Users/manaumenkos/dev/diplom/transfer/data/shards6_smol:/app/data/lucene
      - /Users/manaumenkos/dev/diplom/transfer/data/shards6_smol/output:/data/faiss
    ports:
      - "9096:9096"
    depends_on:
      - clusterstateapi
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
