version: '3.8'

services:
  clusterstateapi:
    image: cluster-state-api:latest
    container_name: clusterstateapi
    ports:
      - "9091:9091"
    networks:
      - mynet

  searchgatewayapi:
    image: search-gateway-api:latest
    container_name: searchgatewayapi
    environment:
      - CLUSTER_STATE_HOST=clusterstateapi
    ports:
      - "8080:8080"
    depends_on:
      - clusterstateapi
    networks:
      - mynet



#  shardsearchservice-2:
#    image: shard-search-api:latest
#    container_name: shardsearchservice-2
#    environment:
#      - NODE_ID=node-2
#      - CLUSTER_STATE_HOST=clusterstateapi
#      - PORT=9092
#    volumes:
#      - ./data2/lucene:/app/data/lucene
#      - ./data2/lucene/output:/app/data/faiss
#    ports:
#      - "9092:9092"
#    depends_on:
#      - clusterstateapi
#    networks:
#      - mynet

#  shardsearchservice-1:
#    image: shard-search-api:latest
#    container_name: shardsearchservice-1
#    environment:
#      - NODE_ID=node-1
#      - CLUSTER_STATE_HOST=clusterstateapi
#      - PORT=9090
#    volumes:
#      - /d/dev/diplom/shard-search-api/data/lucene:/app/data/lucene
#      - /d/dev/diplom/shard-search-api/data/lucene/output:/data/faiss
#    ports:
#      - "9090:9090"
#    depends_on:
#      - clusterstateapi
#    networks:
#      - mynet

  shardsearchservice-2:
    image: shard-search-api:latest
    container_name: shardsearchservice-2
    environment:
      - NODE_ID=node-2
      - CLUSTER_STATE_HOST=clusterstateapi
      - PORT=9092
      - FAISS_SHARD_IDS=0,2
    volumes:
      - ./data/lucene:/app/data/lucene
      - ./data/lucene/output:/data/faiss
    ports:
      - "9092:9092"
    depends_on:
      - clusterstateapi
    networks:
      - mynet

  shardsearchservice-1:
    image: shard-search-api:latest
    container_name: shardsearchservice-1
    environment:
      - NODE_ID=node-1
      - CLUSTER_STATE_HOST=clusterstateapi
      - PORT=9090
      - FAISS_SHARD_IDS=0,1
    volumes:
      - ./data2/lucene:/app/data/lucene
      - ./data2/lucene/output:/data/faiss
    ports:
      - "9090:9090"
    depends_on:
      - clusterstateapi
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
