# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/faiss_search_api.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'api/faiss_search_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61pi/faiss_search_api.proto\x12\x05\x66\x61iss\"B\n\x12\x46\x61issSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\t\n\x01k\x18\x02 \x01(\x05\x12\x12\n\nnormalized\x18\x03 \x01(\x08\"(\n\x0b\x46\x61issResult\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x02\":\n\x13\x46\x61issSearchResponse\x12#\n\x07results\x18\x01 \x03(\x0b\x32\x12.faiss.FaissResult\"\x1e\n\rEncodeRequest\x12\r\n\x05query\x18\x01 \x01(\t\"-\n\x0c\x45ncodedQuery\x12\x1d\n\x06vector\x18\x01 \x01(\x0b\x32\r.faiss.Vector\"\x18\n\x06Vector\x12\x0e\n\x06values\x18\x01 \x03(\x02\x32\x8f\x01\n\x12\x46\x61issSearchService\x12?\n\x06search\x12\x19.faiss.FaissSearchRequest\x1a\x1a.faiss.FaissSearchResponse\x12\x38\n\x0b\x65ncodeQuery\x12\x14.faiss.EncodeRequest\x1a\x13.faiss.EncodedQueryB\x17\n\x13ru.nms.diplom.faissP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.faiss_search_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023ru.nms.diplom.faissP\001'
  _globals['_FAISSSEARCHREQUEST']._serialized_start=37
  _globals['_FAISSSEARCHREQUEST']._serialized_end=103
  _globals['_FAISSRESULT']._serialized_start=105
  _globals['_FAISSRESULT']._serialized_end=145
  _globals['_FAISSSEARCHRESPONSE']._serialized_start=147
  _globals['_FAISSSEARCHRESPONSE']._serialized_end=205
  _globals['_ENCODEREQUEST']._serialized_start=207
  _globals['_ENCODEREQUEST']._serialized_end=237
  _globals['_ENCODEDQUERY']._serialized_start=239
  _globals['_ENCODEDQUERY']._serialized_end=284
  _globals['_VECTOR']._serialized_start=286
  _globals['_VECTOR']._serialized_end=310
  _globals['_FAISSSEARCHSERVICE']._serialized_start=313
  _globals['_FAISSSEARCHSERVICE']._serialized_end=456
# @@protoc_insertion_point(module_scope)
