# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: faiss_search_api.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'faiss_search_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x66\x61iss_search_api.proto\x12\x05\x66\x61iss\"B\n\x12\x46\x61issSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\t\n\x01k\x18\x02 \x01(\x05\x12\x12\n\nnormalized\x18\x03 \x01(\x08\"(\n\x0b\x46\x61issResult\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x02\":\n\x13\x46\x61issSearchResponse\x12#\n\x07results\x18\x01 \x03(\x0b\x32\x12.faiss.FaissResult\"\xa4\x01\n\x11SimilarityRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12>\n\x0cid_to_vector\x18\x02 \x03(\x0b\x32(.faiss.SimilarityRequest.IdToVectorEntry\x1a@\n\x0fIdToVectorEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.faiss.Vector:\x02\x38\x01\"z\n\x12SimilarityResponse\x12\x35\n\x06scores\x18\x01 \x03(\x0b\x32%.faiss.SimilarityResponse.ScoresEntry\x1a-\n\x0bScoresEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\x18\n\x06Vector\x12\x0e\n\x06values\x18\x01 \x03(\x02\x32\xa1\x01\n\x12\x46\x61issSearchService\x12?\n\x06search\x12\x19.faiss.FaissSearchRequest\x1a\x1a.faiss.FaissSearchResponse\x12J\n\x13getSimilarityScores\x12\x18.faiss.SimilarityRequest\x1a\x19.faiss.SimilarityResponseB\x17\n\x13ru.nms.diplom.faissP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'faiss_search_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023ru.nms.diplom.faissP\001'
  _globals['_SIMILARITYREQUEST_IDTOVECTORENTRY']._loaded_options = None
  _globals['_SIMILARITYREQUEST_IDTOVECTORENTRY']._serialized_options = b'8\001'
  _globals['_SIMILARITYRESPONSE_SCORESENTRY']._loaded_options = None
  _globals['_SIMILARITYRESPONSE_SCORESENTRY']._serialized_options = b'8\001'
  _globals['_FAISSSEARCHREQUEST']._serialized_start=33
  _globals['_FAISSSEARCHREQUEST']._serialized_end=99
  _globals['_FAISSRESULT']._serialized_start=101
  _globals['_FAISSRESULT']._serialized_end=141
  _globals['_FAISSSEARCHRESPONSE']._serialized_start=143
  _globals['_FAISSSEARCHRESPONSE']._serialized_end=201
  _globals['_SIMILARITYREQUEST']._serialized_start=204
  _globals['_SIMILARITYREQUEST']._serialized_end=368
  _globals['_SIMILARITYREQUEST_IDTOVECTORENTRY']._serialized_start=304
  _globals['_SIMILARITYREQUEST_IDTOVECTORENTRY']._serialized_end=368
  _globals['_SIMILARITYRESPONSE']._serialized_start=370
  _globals['_SIMILARITYRESPONSE']._serialized_end=492
  _globals['_SIMILARITYRESPONSE_SCORESENTRY']._serialized_start=447
  _globals['_SIMILARITYRESPONSE_SCORESENTRY']._serialized_end=492
  _globals['_VECTOR']._serialized_start=494
  _globals['_VECTOR']._serialized_end=518
  _globals['_FAISSSEARCHSERVICE']._serialized_start=521
  _globals['_FAISSSEARCHSERVICE']._serialized_end=682
# @@protoc_insertion_point(module_scope)
